Merge upstream master, upgrade OSCAL 1.0.0
18F/fedramp-automation pull request #117
Opened 2021-07-07 17:52 UTC by danielnaab

2021-07-07 18:19 UTC, ohsh6o requested changes

2021-07-07 18:19 UTC, ohsh6o commented on .gitmodules
> -	branch = master
B: My bad, can you restore this?

2021-07-07 19:17 UTC, ohsh6o requested changes
This is looking great! Can I make one more request? I just [compared against upstream](https://github.com/GSA/fedramp-automation/compare/master...18F:upgrade-oscal-1.0.0) and only 91 files changed (and only the things we care about. Nice work!

Can you please update for the one last change I made to the `fedramp1.0.0-oscal1.0.0` release tag (there is a commit I pushed to the release after we paired) and fix relevant tests? Thanks!

2021-07-07 19:26 UTC, danielnaab commented
> Can you please update for the one last change I made to the `fedramp1.0.0-oscal1.0.0` release tag (there is a commit I pushed to the release after we paired) and fix relevant tests? Thanks!

Sure - would it be possible to merge that to `GSA/master` first? (for sanity, because this branch includes a merge from master)

2021-07-07 19:42 UTC, ohsh6o commented
> Sure - would it be possible to merge that to `GSA/master` first? (for sanity, because this branch includes a merge from master)

OK, fine by me.

2021-07-07 19:42 UTC, ohsh6o approved these changes

2021-07-08 22:32 UTC, merged

2021-07-14 13:16 UTC, GaryGapinski commented
Validations work against the `fedramp1.0.0-oscal1.0.0` version.

I found and corrected some Schematron tests while reviewing the validations. I'll commit the corrections later this morning.