Include source document title in validation report UI
18F/fedramp-automation pull request #217
Opened 2021-08-17 21:27 UTC by danielnaab

Implementing #119, this adds the document title and current assertion view to the report UI.

Federalist link: https://federalist-2372d2fd-fc94-42fe-bcc7-a8af4f664a51.app.cloud.gov/preview/18f/fedramp-automation/source-doc-data/#/validator

2021-08-17 23:59 UTC, GaryGapinski approved these changes
Actual UI presents desired outcome.

2021-08-18 01:52 UTC, ohsh6o requested changes
I thought we agreed on `system-name`, _not_ `metadata/title`?

UPDATE: I checked 18F#215, we include both in the SVRL, so either could easily be supported. Did we not agree system name over title in standup this morning?

2021-08-18 03:10 UTC, ohsh6o approved these changes

2021-08-18 03:10 UTC, danielnaab commented
> I thought we agreed on `system-name`, _not_ `metadata/title`?
> 
> UPDATE: I checked #215, we include both in the SVRL, so either could easily be supported. Did we not agree system name over title in standup this morning?

I'm sure I got mixed up - updated.

2021-08-18 03:17 UTC, merged