Update CONTRIBUTING.md
18F/fedramp-automation pull request #395
Opened 2022-03-16 15:03 UTC by GaryGapinski

Closes #394.

2022-03-18 13:47 UTC, markXLIX approved these changes
We could make these more general to all IDEs but this is sufficient for now.

Thoughts on being more specific in the 'Sort attributes' to 'Alpha sort attributes'?

Neither of these comments are meant as show stoppers.  This can be merged.

2022-03-29 16:28 UTC, danielnaab approved these changes

2022-03-29 17:46 UTC, danielnaab requested changes

2022-03-29 17:46 UTC, danielnaab commented on src/validations/CONTRIBUTING.md
> +`-s directoryName` Schematron directory used to validate the file, ex: `-o ~/mySchematronDirectiry`. Each `.sch` document found within the specified directory will be compliled and generate a separat
```suggestion
`-s directoryName` Schematron directory used to validate the file, ex: `-o ~/mySchematronDirectory`. Each `.sch` document found within the specified directory will be compliled and generate a separate report. If omitted, defaults to the src relative to the parent of the bin directory where this script is located.
```

2022-03-29 17:47 UTC, danielnaab approved these changes

2022-03-30 00:11 UTC, merged