157 dmarc config identified
18F/fedramp-automation pull request #397
Opened 2022-03-18 19:22 UTC by markXLIX

2022-03-22 11:20 UTC, GaryGapinski commented on src/validations/rules/ssp.sch
> +            <sch:report
Why is this a `report` rather than an `assert`?

2022-03-22 11:36 UTC, GaryGapinski commented on src/validations/rules/ssp.sch
> +                value="'email', 'e-mail', 'electronic mail'" />
I am uncertain this will result in a sequence.

2022-03-22 12:34 UTC, GaryGapinski commented on src/validations/rules/ssp.sch
> +                    if (//*[lower-case(.) = $emailString])
The document
```
<ssp>
    <p>email is used.</p>
</ssp>
```
assessed using the XPath expression
```
//*[lower-case(.) = ('email', 'e-mail', 'electronic mail')]
```
will be considered to not have the word "email".

The document
```
<ssp>
    <p>email</p>
</ssp>
```
would. But both documents mention email.

2022-03-23 15:51 UTC, GaryGapinski commented
The current assertion message is "_This FedRAMP SSP has references to 'email', 'e-mail', or 'electronic mail'._". That message is incorrect if there is no mention of electronic mail in the SSP.

I think the assertion message should somehow express the two factors contributing to a positive outcome, namely

1. The SSP does not mention electronic mail, or
2. The SSP mentions electronic mail and also mentions SPF, DKIM, and DMARC

as opposed to asserting just the second. Perhaps something like "_Electronic mail is either absent or sufficiently specified._".

The current diagnostic message is _"DMARC, SPF, and DKIM is referenced in this SSP._". That message is incorrect when the assertion fails.

If the assertion fails, an "analogous negation" message would be something like "_Electronic mail is present but appears to lack documentation of SPF, DKIM, and DMARC._".

2022-03-23 17:46 UTC, markXLIX commented
My reading of the task was that email without DMARC, etc was the only desired hit.  I worded the message as the positive because I thought that was the desired output.  The user only wanted to know when these all occurred as stated so they did not need to go looking for them.

I am in the process of adjusting the code to match your reading.

2022-03-29 03:23 UTC, GaryGapinski requested changes

2022-03-29 03:23 UTC, GaryGapinski commented on src/validations/rules/ssp.sch
>                          (true())">This FedRAMP SSP references 'email', 'e-mail', or 'electronic mail'.</sch:assert>
This positive test result assertion message (**_This FedRAMP SSP references 'email', 'e-mail', or 'electronic mail'._**)remains incorrect. It does not address the absence within the SSP of any mention of email.

Please see previous comments regarding positive test outcome assertion messages.

2022-03-31 00:13 UTC, GaryGapinski approved these changes
Looks good to go.

2022-03-31 12:48 UTC, merged