Added banned items per 2022-03-25 update
18F/fedramp-automation pull request #404
Opened 2022-03-28 14:56 UTC by markXLIX

https://www.fcc.gov/supplychain/coveredlist

2022-03-28 18:01 UTC, GaryGapinski requested changes
The assertion` inventory-item-has-prohibited-vendor-name` message is incorrect for a successful test outcome (i.e., it does not conform to the acceptance criterion "All Schematron assertion messages are declarative statements which affirm the positive test outcome.").

The assertion id itself does not follow the same manner as (most) other assertions, namely, stating the positive outcome, but that can be relegated to a separate issue to fix all such "negative" identifiers and need not be corrected here.

2022-03-29 02:20 UTC, GaryGapinski commented on src/validations/rules/ssp.sch
>              <sch:assert
This assertion fails to exhibit a correct message for a postive test outcome.

The acceptance criterion is "**All Schematron assertion messages are declarative statements which affirm the positive test outcome.**".

The message you are proposing is "**The information system contains a banned vendor -  '<xsl:value-of select="o:prop[@name eq 'vendor-name']/@value"/>'.  See FAR 889(a)(1)(B)**.". When this assertion test - `not(o:prop[@name eq 'vendor-name']/@value = $prohibit-vendor)` - i.e., encounters an `<inventory-item>` `<prop name="vendor">` which is not a banned value, is positive (boolean true) for any `<inventory-item>` the Schematron result (SVRL output) will have the assertion message citing the value as banned when it is not.

When the assertion is successful, the message will be incorrect and additionally cite the correct vendor-name value as being a banned one.

A sample positive assertion message would be something like "_The inventory item does not cite a banned vendor._".

Let's discuss this tomorrow if questions remain.

2022-04-01 12:28 UTC, markXLIX commented
closes #403

2022-04-01 16:28 UTC, GaryGapinski approved these changes
Looks good.

I am unsure you can put a "closes \#nnn" in a comment as opposed to the issue description, but try it and see.

2022-04-01 17:23 UTC, markXLIX commented
That was my thought about the 'closes ####' but I figured it couldn't hurt to try it.

2022-04-01 17:23 UTC, merged