feat: check include and exclude subjects of component assessment-subj…
18F/fedramp-automation pull request #571
Opened 2022-06-29 13:55 UTC by markXLIX

Check include and exclude subject elements of component assessment-subject elements for matching SSP component or SAP inventory-items

closes #568

2022-06-29 14:16 UTC, danielnaab commented on src/validations/rules/sap.sch
> +        </sch:rule>
Is it possible to write xspec for this?

2022-07-08 14:05 UTC, danielnaab approved these changes

2022-07-11 12:37 UTC, GaryGapinski requested changes

2022-07-11 14:59 UTC, markXLIX commented on src/validations/rules/sap.sch
> +                (())" />
reuse of previous code.  This is fixed.

2022-07-11 15:14 UTC, GaryGapinski approved these changes

2022-07-11 15:39 UTC, merged