Issue 628 included activities
18F/fedramp-automation pull request #630
Opened 2022-07-22 13:09 UTC by markXLIX

Added asserts, diagnostics, xspec for:
terms-and-conditions/part[@name='included-activities']
part[@name='included-activities']/part[@name='included-activity']

formatting

2022-07-22 18:15 UTC, danielnaab requested changes
Minor wording suggestions

2022-07-22 18:15 UTC, danielnaab commented on src/validations/rules/sap.sch
> +                test="deep-equal($unsorted_assumptions, $sorted_assumptions)">The SAP terms and conditions assumptions part has assumption parts that
```suggestion
                test="deep-equal($unsorted_assumptions, $sorted_assumptions)">The SAP terms and conditions assumptions part must have assumption parts that
```

2022-07-22 18:15 UTC, danielnaab commented on src/validations/rules/sap.sch
> +                test="oscal:part[@name eq 'included-activity']">The SAP Rules of Engagement (ROE) included activities have one or more included
```suggestion
                test="oscal:part[@name eq 'included-activity']">The SAP Rules of Engagement (ROE) included activities must have one or more included
```

2022-07-22 18:15 UTC, danielnaab commented on src/validations/test/rules/sap.xspec
> +                    label="and there is not an include-all child element">
```suggestion
                    label="when there is not an include-all child element">
```

2022-07-22 18:15 UTC, danielnaab commented on src/validations/test/rules/sap.xspec
> +                    label="there is not a role element with an @id of 'assessor'">
```suggestion
                    label="when there is not a role element with an @id of 'assessor'">
```

2022-09-05 12:52 UTC, GaryGapinski approved these changes

2022-09-12 19:23 UTC, danielnaab approved these changes

2022-09-12 20:55 UTC, merged