feat: SAR Observations and Evidence
18F/fedramp-automation pull request #647
Opened 2022-08-11 12:33 UTC by markXLIX

* Generalize comparison of oscal:actor[@type='party'] to all oscal:actor elements - compare to SAP and SAR party assemblies
* Any observation with a type of 'control-objective' must have a subject that has a @subject-uuid that points to a resource/@uuid in the SAR back-matter.
* Any observation with a type of 'control-objective' must have an origin/related-task with a @task-uuid that points to the task in the SAP.
* Acceptable values of method as 'EXAMINE, INTERVIEW, TEST'
* Acceptable values of subject/@type are ' component, inventory-item, location, party, or user'
* Acceptable values of origin/actor/@type are 'tool, party, or assessment-platform'
* minor formatting and narrative changes

2022-08-19 15:53 UTC, danielnaab requested changes

2022-08-19 15:53 UTC, danielnaab commented on src/validations/rules/sar.sch
> +                    select="../../local-name()" /> has an actor who is described in a SAP or SAR party assembly.</sch:assert>
```suggestion
                    select="../../local-name()" /> must have an actor who is described in a SAP or SAR party assembly.</sch:assert>
```

2022-08-19 15:53 UTC, danielnaab commented on src/validations/rules/sar.sch
> +                test="@type[. = $actorTypes]">The actor @type has one of the following as string content: 'tool', 'party', or
```suggestion
                test="@type[. = $actorTypes]">The actor @type must have one of the following as string content: 'tool', 'party', or
```

2022-08-19 15:53 UTC, danielnaab commented on src/validations/rules/sar.sch
> +                test="@type[. = $subjectValues]">A subject element type attribute contains one of the following as string content: 'component',
```suggestion
                test="@type[. = $subjectValues]">A subject element type attribute must contain one of the following as string content: 'component',
```

2022-08-19 15:53 UTC, danielnaab commented on src/validations/rules/sar.sch
> +                        true()">A subject uuid within an observation of type 'control-objective' has a matching resource @uuid in the
```suggestion
                        true()">A subject uuid within an observation of type 'control-objective' must have a matching resource @uuid in the
```

2022-08-19 15:53 UTC, danielnaab commented on src/validations/rules/sar.sch
> +                test=". = $methodValues">A method element contains one of the following strings: 'EXAMINE', 'INTERVIEW', or 'TEST'.</sch:assert>
```suggestion
                test=". = $methodValues">A method element must contain one of the following strings: 'EXAMINE', 'INTERVIEW', or 'TEST'.</sch:assert>
```

2022-08-19 15:53 UTC, danielnaab commented on src/validations/rules/sar.sch
> +                unit:override-xspec="both">A related-task element's uuid attribute matches a task @uuid value in the associated SAP.</sch:assert>
```suggestion
                unit:override-xspec="both">A related-task element's uuid attribute must match a task @uuid value in the associated SAP.</sch:assert>
```

2022-08-19 15:53 UTC, danielnaab commented on src/validations/rules/sar.sch
>              id="has-import-ap-diagnostic">This OSCAL SAR lacks have an import-ap element.</sch:diagnostic>
```suggestion
            id="has-import-ap-diagnostic">This OSCAL SAR lacks an import-ap element.</sch:diagnostic>
```

2022-09-06 09:52 UTC, GaryGapinski approved these changes

2022-09-12 19:22 UTC, danielnaab approved these changes

2022-09-13 14:14 UTC, merged