feat: Interview SAR items
18F/fedramp-automation pull request #650
Opened 2022-08-11 16:54 UTC by markXLIX

Close #648 

Match subject-reference uuid values against the SSP, SAP, SAR party metadata uuid values.

Example of handling of relevant-evidence.  However, commented out.  The Guide is not at all clear on usage of the @href in this context.

2022-08-19 15:47 UTC, danielnaab requested changes

2022-09-06 10:00 UTC, GaryGapinski approved these changes

2022-09-06 10:00 UTC, GaryGapinski commented on src/validations/rules/sar.sch
> +                select="../@uuid" />, has a relevent-evidence href, <sch:value-of
Typo "relevent".

2022-09-08 16:11 UTC, markXLIX commented on src/validations/rules/sar.sch
> +                select="../@uuid" />, has a relevent-evidence href, <sch:value-of
fixed

2022-09-12 19:22 UTC, danielnaab approved these changes

2022-09-13 15:47 UTC, merged