Issue 653 SAR implementation statement differential
18F/fedramp-automation pull request #655
Opened 2022-08-16 17:37 UTC by markXLIX

closes #653 
* observation of type 'ssp-statement-issue' has method of 'EXAMINE'
* observation of type 'ssp-statement-issue has uuid that matches a finding/related-observation/observation-uuid.
* finding/related-observation/observation-uuid that matches a observation of type 'ssp-statement-issue' uuid has an implementation-statement-uuid value that matches a statement uuid value in the associated SSP.

2022-08-19 15:30 UTC, danielnaab requested changes

2022-08-19 15:30 UTC, danielnaab commented on src/validations/rules/sar.sch
> +                        true()">An observation with a type of 'ssp-statement-issue' also has a method of 'EXAMINE'.</sch:assert>
```suggestion
                        true()">An observation with a type of 'ssp-statement-issue' must also have a method of 'EXAMINE'.</sch:assert>
```

2022-08-19 15:30 UTC, danielnaab commented on src/validations/rules/sar.sch
> +                        true()">An observation with a type of 'ssp-statement-issue' has a matching
```suggestion
                        true()">An observation with a type of 'ssp-statement-issue' must have a matching
```

2022-08-19 15:30 UTC, danielnaab commented on src/validations/rules/sar.sch
> +                unit:override-xspec="both">The finding that has a related-observation/observation-uuid that matches an observation/@uuid, also has a implementation-statement-uuid value that
```suggestion
                unit:override-xspec="both">The finding that has a related-observation/observation-uuid that matches an observation/@uuid, must also have a implementation-statement-uuid value that 
```

2022-09-06 10:23 UTC, GaryGapinski approved these changes
It appears that whoever was drafting SAR stuff did not take into account that an SSP undergoes change and there is no apparent place at which the SSP version at the time of assessment is captured.

2022-09-12 19:21 UTC, danielnaab approved these changes

2022-09-13 18:50 UTC, merged