feat: SAR-Identified Risks
18F/fedramp-automation pull request #657
Opened 2022-08-16 21:02 UTC by markXLIX

* A finding with a target/status/@State of 'not-satisfied' must have at least one associated-risk child
*Any associated-risk must have a @risk-uuid value that points to a risk/@uuid value in the SAR.
* Each risk assembly must have an characterization with children facet elements of @System='https://fedramp.gov' AND  @name='likelihood' AND @System='https://fedramp.gov' and @name='impact').
* Each facet (likelihood' or 'impact' and 'https://fedramp.gov') have a @value of 'low', 'moderate', or 'high'

2022-08-19 15:28 UTC, danielnaab requested changes

2022-08-19 15:28 UTC, danielnaab commented on src/validations/rules/sar.sch
> +                        true()">A finding with a target/status of 'not-satisfied has an associated-risk element.</sch:assert>
```suggestion
                        true()">A finding with a target/status of 'not-satisfied must have an associated-risk element.</sch:assert>
```

2022-08-19 15:28 UTC, danielnaab commented on src/validations/rules/sar.sch
> +                test="@risk-uuid[. = $SAR-risk-uuids]">An associated-risk/@risk-uuid has a matching risk/@uuid in the SAR.</sch:assert>
```suggestion
                test="@risk-uuid[. = $SAR-risk-uuids]">An associated-risk/@risk-uuid must have a matching risk/@uuid in the SAR.</sch:assert>
```

2022-08-19 15:28 UTC, danielnaab commented on src/validations/rules/sar.sch
> +                test="">Each characterization has pairs of facet elements where the @name is 'likelihood' or 'impact' and the child prop[@name='state'] have the same @value values.</sch:assert>
```suggestion
                test="">Each characterization must have pairs of facet elements where the @name is 'likelihood' or 'impact' and the child prop[@name='state'] have the same @value values.</sch:assert>
```

2022-08-19 15:28 UTC, danielnaab commented on src/validations/rules/sar.sch
> +                with @name of 'likelihood' and @name='impact' exist in the characterization.</sch:assert>
```suggestion
                with @name of 'likelihood' and @name='impact' must exist in the characterization.</sch:assert>
```

2022-08-19 15:28 UTC, danielnaab commented on src/validations/rules/sar.sch
> +                        true()">facet with either @name = 'likelihood' or @name='impact' has an @value of either 'low', 'moderate', or
```suggestion
                        true()">A facet with @name = 'likelihood' or @name='impact' must have an @value of either 'low', 'moderate', or
```

2022-09-06 10:32 UTC, GaryGapinski approved these changes
SAR documentation does not indicate `impact` is required (The POA&M guide does).

2022-09-12 19:20 UTC, danielnaab approved these changes

2022-09-13 19:02 UTC, merged