remove inventory-item-has-purpose
18F/fedramp-automation pull request #717
Opened 2022-10-24 18:12 UTC by markXLIX

Removed assertions and xspec for:
inventory-item-has-purpose
inventory-item-has-sufficient-purpose

2022-10-24 18:53 UTC, danielnaab approved these changes
Could you add a link to the issue this implements?

2022-10-25 14:18 UTC, GaryGapinski requested changes
These documents have not been formatted and indented. Looks like that was also the case prior to this PR.

2022-10-25 14:25 UTC, markXLIX commented
> These documents have not been formatted and indented. Looks like that was also the case prior to this PR.

I just attempted to format them within oXygen.  There was no change to the documents after applying the formatting.  I've noticed that the formatting has come undone when accepting changes within github.  Perhaps this occurred during a previous PR?

We should take a look.

2022-10-26 06:10 UTC, GaryGapinski approved these changes

2022-10-26 14:17 UTC, merged