fixed typo in interconnection assertions
18F/fedramp-automation pull request #718
Opened 2022-10-24 18:15 UTC by markXLIX

changed 'agreement' to 'isa-agreement' in shematron and xspec

2022-10-24 18:52 UTC, danielnaab approved these changes

2022-10-25 14:30 UTC, GaryGapinski requested changes
Once again, no format and indent has been done. Looks like a prior PR also lacked formatting.

2022-10-25 14:32 UTC, markXLIX commented
> Once again, no format and indent has been done. Looks like a prior PR also lacked formatting.

See my reply here. [https://github.com/18F/fedramp-automation/pull/717#issuecomment-1290643660](https://github.com/18F/fedramp-automation/pull/717#issuecomment-1290643660)

2022-10-25 21:52 UTC, GaryGapinski approved these changes

2022-10-26 06:09 UTC, GaryGapinski approved these changes

2022-10-26 14:40 UTC, merged